<?php

namespace CYA\YogaBundle\Repository;

/**
 * AlumnoccRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnoccRepository extends \Doctrine\ORM\EntityRepository
{
}
