<?php

namespace CYA\YogaBundle\Repository;

/**
 * auxiliarventaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class auxiliarventaRepository extends \Doctrine\ORM\EntityRepository
{
}
