<?php

namespace CYA\YogaBundle\Repository;

/**
 * CursadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursadaRepository extends \Doctrine\ORM\EntityRepository
{ 
    public function findOneByUsuario($id)
    {
        return  $this->createQueryBuilder('cursada')
            ->where('cursada.usuario = :id')->setParameter('id', $id)
            ->getQuery()->getResult();
    
    }

    public function findOneByMateria($id)
    {
        return  $this->createQueryBuilder('cursada')
            ->where('cursada.materia = :id')->setParameter('id', $id)
            ->getQuery()->getResult();
    
    }


    public function findOneByMateriaAndUser($materia, $userid)
    {
        return  $this->createQueryBuilder('cursada')
            ->where('cursada.materia = :materia')->setParameter('materia', $materia)
            ->andWhere('cursada.usuario = :userid')->setParameter('userid', $userid)
            ->getQuery()->getResult();
    
    }
   





}
