<?php

namespace CYA\YogaBundle\Repository;

/**
 * DetalleventaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleventaRepository extends \Doctrine\ORM\EntityRepository
{
}
