<?php

namespace CYA\YogaBundle\Repository;

/**
 * LockerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LockerRepository extends \Doctrine\ORM\EntityRepository
{
}
