<?php

namespace CYA\YogaBundle\Repository;

/**
 * LockersocioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LockersocioRepository extends \Doctrine\ORM\EntityRepository
{
}
