<?php

namespace CYA\YogaBundle\Repository;

/**
 * MaestroventaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaestroventaRepository extends \Doctrine\ORM\EntityRepository
{
}
