<?php

namespace CYA\YogaBundle\Repository;

/**
 * MovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoRepository extends \Doctrine\ORM\EntityRepository
{
    
      public function findLastId()
    {
         return  $this->createQueryBuilder('movimiento')
           
            ->setMaxResults(1)  
            ->orderBy('movimiento.id', 'DESC')
            ->getQuery()->getOneOrNullResult();
    
            
            
        //   return $this->createQueryBuilder('s')
        //     ->select('s, MAX(s.id) AS HIDDEN max_score')
        //     ->groupBy('s.id')
        //     ->orderBy('max_score', 'DESC');
        
    
    }  
    
    
}
