<?php

namespace CYA\YogaBundle\Repository;

/**
 * ProveedorccRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorccRepository extends \Doctrine\ORM\EntityRepository
{
}
