<?php

namespace CYA\YogaBundle\Repository;

/**
 * RubroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubroRepository extends \Doctrine\ORM\EntityRepository
{
}
