<?php

namespace CYA\YogaBundle\Repository;

/**
 * TipocuotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipocuotaRepository extends \Doctrine\ORM\EntityRepository
{
}
