<?php

namespace CYA\YogaBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
    
     public function findOneByDni($dni)
    {
        return  $this->createQueryBuilder('Usuario')
            ->where('Usuario.dni = :dni')->setParameter('dni', $dni)
            ->getQuery()->getOneOrNullResult();
    
}}
