cya_cursada_index:
    path:    /index
    defaults: { _controller: CYAYogaBundle:Cursada:index }
    
cya_cursada_add:
    path:    /add/{id}
    defaults: { _controller: CYAYogaBundle:Cursada:add }
    methods: [POST,GET]

cya_cursada_create:
    path:    /create
    defaults: { _controller: CYAYogaBundle:Cursada:create }
    methods: POST

cya_cursada_edit:
    path:    /edit/{id}
    defaults: { _controller: CYAYogaBundle:Cursada:edit }
    
cya_cursada_update:
    path:    /update/{id}
    defaults: { _controller: CYAYogaBundle:Cursada:update }
    methods: [POST,PUT]
    
cya_cursada_view:
    path:    /view/{id}
    defaults: { _controller: CYAYogaBundle:Cursada:view }
    
cya_cursada_delete:
    path:    /delete/{id}
    defaults: { _controller: CYAYogaBundle:Cursada:delete }
    
    