cya_detalleventa_add:
    path:    /add
    defaults: { _controller: CYAYogaBundle:Detalleventa:add }
    
cya_detalleventa_delete:
    path:    /delete/{id}
    defaults: { _controller: CYAYogaBundle:Detalleventa:delete }