cya_materia_index:
    path:    /index
    defaults: { _controller: CYAYogaBundle:Materia:index }
    
cya_materia_add:
    path:    /add
    defaults: { _controller: CYAYogaBundle:Materia:add }

cya_materia_create:
    path:    /create
    defaults: { _controller: CYAYogaBundle:Materia:create }
    methods: POST

cya_materia_edit:
    path:    /edit/{id}
    defaults: { _controller: CYAYogaBundle:Materia:edit }
    
cya_materia_update:
    path:    /update/{id}
    defaults: { _controller: CYAYogaBundle:Materia:update }
    methods: [POST,PUT]
    
cya_materia_view:
    path:    /view/{id}
    defaults: { _controller: CYAYogaBundle:Materia:view }
    
cya_materia_delete:
    path:    /delete/{id}
    defaults: { _controller: CYAYogaBundle:Materia:delete }
    
    