cya_tipocuota_index:
    path:    /index
    defaults: { _controller: CYAYogaBundle:Tipocuota:index }
    
cya_tipocuota_add:
    path:    /add
    defaults: { _controller: CYAYogaBundle:Tipocuota:add }

cya_tipocuota_edit:
    path:    /edit/{id}
    defaults: { _controller: CYAYogaBundle:Tipocuota:edit }

cya_tipocuota_delete:
    path:    /delete/{id}
    defaults: { _controller: CYAYogaBundle:Tipocuota:delete }