cya_usuario_index:
    path:    /index
    defaults: { _controller: CYAYogaBundle:Usuario:index }
    
cya_usuario_add:
    path:    /add
    defaults: { _controller: CYAYogaBundle:Usuario:add }

cya_usuario_rapido:
    path:    /rapido
    defaults: { _controller: CYAYogaBundle:Usuario:usuariorapido }
    
cya_usuario_create:
    path:    /create
    defaults: { _controller: CYAYogaBundle:Usuario:create }
    methods: POST

cya_usuario_edit:
    path:    /edit/{id}
    defaults: { _controller: CYAYogaBundle:Usuario:edit }

cya_usuario_editavatar:
    path:    /editavatar/{id}
    defaults: { _controller: CYAYogaBundle:Usuario:editavatar }    
    
cya_usuario_editpublic:
    path:    /editpublic/
    defaults: { _controller: CYAYogaBundle:Usuario:editpublic }

cya_usuario_editpass:
    path:    /editpass/{id}
    defaults: { _controller: CYAYogaBundle:Usuario:editpass }    
    
cya_usuario_update:
    path:    /update/{id}
    defaults: { _controller: CYAYogaBundle:Usuario:update }
    methods: [POST,PUT]
    
cya_usuario_view:
    path:    /view/{id}
    defaults: { _controller: CYAYogaBundle:Usuario:view }
    
cya_usuario_inicio:
    path:    /inicio
    defaults: { _controller: CYAYogaBundle:Usuario:inicio }
    
cya_usuario_constru:
    path:    /constru
    defaults: { _controller: CYAYogaBundle:Usuario:constru }
    
cya_usuario_generarcuota:
    path:    /generarcuota
    defaults: { _controller: CYAYogaBundle:Usuario:generarcuota }

cya_usuario_imprimircuota:
    path:    /imprimircuota/{id}
    defaults: { _controller: CYAYogaBundle:Usuario:imprimircuota }    
    
cya_usuario_imprimircuota2:
    path:    /imprimircuota2/{id}/{valorcuota}/{mes}/{cc}
    defaults: { _controller: CYAYogaBundle:Usuario:imprimircuota2 }    