<?php

namespace Proxies\__CG__\CYA\YogaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Proveedor extends \CYA\YogaBundle\Entity\Proveedor implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'proveedorcc', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedor' . "\0" . 'id', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedor' . "\0" . 'nombre', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedor' . "\0" . 'mail', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedor' . "\0" . 'telefono', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedor' . "\0" . 'tipo'];
        }

        return ['__isInitialized__', 'proveedorcc', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedor' . "\0" . 'id', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedor' . "\0" . 'nombre', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedor' . "\0" . 'mail', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedor' . "\0" . 'telefono', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedor' . "\0" . 'tipo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Proveedor $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', [$mail]);

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', []);

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function addProducto(\CYA\YogaBundle\Entity\Producto $producto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProducto', [$producto]);

        return parent::addProducto($producto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProducto(\CYA\YogaBundle\Entity\Producto $producto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProducto', [$producto]);

        return parent::removeProducto($producto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductos', []);

        return parent::getProductos();
    }

    /**
     * {@inheritDoc}
     */
    public function addProvedorcc(\CYA\YogaBundle\Entity\Proveedorcc $proveedorcc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProvedorcc', [$proveedorcc]);

        return parent::addProvedorcc($proveedorcc);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProvedorcc(\CYA\YogaBundle\Entity\Proveedorcc $proveedorcc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProvedorcc', [$proveedorcc]);

        return parent::removeProvedorcc($proveedorcc);
    }

    /**
     * {@inheritDoc}
     */
    public function getProveedorccs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProveedorccs', []);

        return parent::getProveedorccs();
    }

    /**
     * {@inheritDoc}
     */
    public function addProveedorcc(\CYA\YogaBundle\Entity\Proveedorcc $proveedorcc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProveedorcc', [$proveedorcc]);

        return parent::addProveedorcc($proveedorcc);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProveedorcc(\CYA\YogaBundle\Entity\Proveedorcc $proveedorcc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProveedorcc', [$proveedorcc]);

        return parent::removeProveedorcc($proveedorcc);
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

}
