<?php

namespace Proxies\__CG__\CYA\YogaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Movimiento extends \CYA\YogaBundle\Entity\Movimiento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'maestroventa', 'proveedorcc', 'alumnocc', 'usuario', 'rubro', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Movimiento' . "\0" . 'id', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Movimiento' . "\0" . 'fecha', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Movimiento' . "\0" . 'descripcion', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Movimiento' . "\0" . 'monto', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Movimiento' . "\0" . 'tipo'];
        }

        return ['__isInitialized__', 'maestroventa', 'proveedorcc', 'alumnocc', 'usuario', 'rubro', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Movimiento' . "\0" . 'id', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Movimiento' . "\0" . 'fecha', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Movimiento' . "\0" . 'descripcion', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Movimiento' . "\0" . 'monto', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Movimiento' . "\0" . 'tipo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Movimiento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaValue', []);

        return parent::setFechaValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonto($monto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonto', [$monto]);

        return parent::setMonto($monto);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonto', []);

        return parent::getMonto();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRubro(\CYA\YogaBundle\Entity\Rubro $rubro = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRubro', [$rubro]);

        return parent::setRubro($rubro);
    }

    /**
     * {@inheritDoc}
     */
    public function getRubro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRubro', []);

        return parent::getRubro();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\CYA\YogaBundle\Entity\Usuario $usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlumnocc(\CYA\YogaBundle\Entity\Alumnocc $alumnocc = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlumnocc', [$alumnocc]);

        return parent::setAlumnocc($alumnocc);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlumnocc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlumnocc', []);

        return parent::getAlumnocc();
    }

    /**
     * {@inheritDoc}
     */
    public function setProveedorcc(\CYA\YogaBundle\Entity\Proveedorcc $proveedorcc = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProveedorcc', [$proveedorcc]);

        return parent::setProveedorcc($proveedorcc);
    }

    /**
     * {@inheritDoc}
     */
    public function getProveedorcc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProveedorcc', []);

        return parent::getProveedorcc();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaestroventa(\CYA\YogaBundle\Entity\Maestroventa $maestroventa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaestroventa', [$maestroventa]);

        return parent::setMaestroventa($maestroventa);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaestroventa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaestroventa', []);

        return parent::getMaestroventa();
    }

}
