<?php

namespace Proxies\__CG__\CYA\YogaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Proveedorcc extends \CYA\YogaBundle\Entity\Proveedorcc implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'proveedor', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedorcc' . "\0" . 'id', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedorcc' . "\0" . 'fechavencimiento', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedorcc' . "\0" . 'deuda', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedorcc' . "\0" . 'pagado', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedorcc' . "\0" . 'factura', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedorcc' . "\0" . 'tipo'];
        }

        return ['__isInitialized__', 'proveedor', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedorcc' . "\0" . 'id', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedorcc' . "\0" . 'fechavencimiento', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedorcc' . "\0" . 'deuda', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedorcc' . "\0" . 'pagado', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedorcc' . "\0" . 'factura', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Proveedorcc' . "\0" . 'tipo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Proveedorcc $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechavencimiento($fechavencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechavencimiento', [$fechavencimiento]);

        return parent::setFechavencimiento($fechavencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechavencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechavencimiento', []);

        return parent::getFechavencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeuda($deuda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeuda', [$deuda]);

        return parent::setDeuda($deuda);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeuda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeuda', []);

        return parent::getDeuda();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagado($pagado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagado', [$pagado]);

        return parent::setPagado($pagado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagado', []);

        return parent::getPagado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFactura($factura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFactura', [$factura]);

        return parent::setFactura($factura);
    }

    /**
     * {@inheritDoc}
     */
    public function getFactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactura', []);

        return parent::getFactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setProveedor(\CYA\YogaBundle\Entity\Proveedor $proveedor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProveedor', [$proveedor]);

        return parent::setProveedor($proveedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getProveedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProveedor', []);

        return parent::getProveedor();
    }

    /**
     * {@inheritDoc}
     */
    public function addMovimiento(\CYA\YogaBundle\Entity\Movimiento $movimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMovimiento', [$movimiento]);

        return parent::addMovimiento($movimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMovimiento(\CYA\YogaBundle\Entity\Movimiento $movimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMovimiento', [$movimiento]);

        return parent::removeMovimiento($movimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovimientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovimientos', []);

        return parent::getMovimientos();
    }

}
