<?php

namespace Proxies\__CG__\CYA\YogaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Producto extends \CYA\YogaBundle\Entity\Producto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'auxiliarventas', 'detalleventas', 'tipoproducto', 'proveedor', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Producto' . "\0" . 'id', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Producto' . "\0" . 'descripcion', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Producto' . "\0" . 'stock', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Producto' . "\0" . 'costo', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Producto' . "\0" . 'preciolista', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Producto' . "\0" . 'isActive'];
        }

        return ['__isInitialized__', 'auxiliarventas', 'detalleventas', 'tipoproducto', 'proveedor', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Producto' . "\0" . 'id', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Producto' . "\0" . 'descripcion', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Producto' . "\0" . 'stock', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Producto' . "\0" . 'costo', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Producto' . "\0" . 'preciolista', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Producto' . "\0" . 'isActive'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Producto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setStock($stock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStock', [$stock]);

        return parent::setStock($stock);
    }

    /**
     * {@inheritDoc}
     */
    public function getStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', []);

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setCosto($costo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCosto', [$costo]);

        return parent::setCosto($costo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCosto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCosto', []);

        return parent::getCosto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreciolista($preciolista)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreciolista', [$preciolista]);

        return parent::setPreciolista($preciolista);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreciolista()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreciolista', []);

        return parent::getPreciolista();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoproducto(\CYA\YogaBundle\Entity\Tipoproducto $tipoproducto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoproducto', [$tipoproducto]);

        return parent::setTipoproducto($tipoproducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoproducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoproducto', []);

        return parent::getTipoproducto();
    }

    /**
     * {@inheritDoc}
     */
    public function setProveedor(\CYA\YogaBundle\Entity\Proveedor $proveedor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProveedor', [$proveedor]);

        return parent::setProveedor($proveedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getProveedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProveedor', []);

        return parent::getProveedor();
    }

    /**
     * {@inheritDoc}
     */
    public function addAuxiliarventa(\CYA\YogaBundle\Entity\Auxiliarventa $auxiliarventa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAuxiliarventa', [$auxiliarventa]);

        return parent::addAuxiliarventa($auxiliarventa);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAuxiliarventa(\CYA\YogaBundle\Entity\Auxiliarventa $auxiliarventa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAuxiliarventa', [$auxiliarventa]);

        return parent::removeAuxiliarventa($auxiliarventa);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuxiliarventas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuxiliarventas', []);

        return parent::getAuxiliarventas();
    }

    /**
     * {@inheritDoc}
     */
    public function addDetalleventa(\CYA\YogaBundle\Entity\Detalleventa $detalleventa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDetalleventa', [$detalleventa]);

        return parent::addDetalleventa($detalleventa);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDetalleventa(\CYA\YogaBundle\Entity\Detalleventa $detalleventa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDetalleventa', [$detalleventa]);

        return parent::removeDetalleventa($detalleventa);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalleventas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalleventas', []);

        return parent::getDetalleventas();
    }

}
