<?php

namespace Proxies\__CG__\CYA\YogaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \CYA\YogaBundle\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'movimientos', 'alumnoccs', 'tipocuota', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'nombreusuario', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'nombre', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'apellido', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'dni', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'direccion', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'ciudad', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'telefono', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'mail', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'fechanacimiento', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'fechaingreso', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'fechareingreso', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'password', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'rol', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'isActive', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'haveLocker', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'haveAsoc', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'createdAt', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'updatedAt', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'brochure'];
        }

        return ['__isInitialized__', 'movimientos', 'alumnoccs', 'tipocuota', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'nombreusuario', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'nombre', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'apellido', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'dni', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'direccion', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'ciudad', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'telefono', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'mail', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'fechanacimiento', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'fechaingreso', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'fechareingreso', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'password', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'rol', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'isActive', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'haveLocker', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'haveAsoc', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'createdAt', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'updatedAt', '' . "\0" . 'CYA\\YogaBundle\\Entity\\Usuario' . "\0" . 'brochure'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getBrochure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrochure', []);

        return parent::getBrochure();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrochure($brochure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrochure', [$brochure]);

        return parent::setBrochure($brochure);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreusuario($nombreusuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreusuario', [$nombreusuario]);

        return parent::setNombreusuario($nombreusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreusuario', []);

        return parent::getNombreusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido($apellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', [$apellido]);

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', []);

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setDni($dni)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDni', [$dni]);

        return parent::setDni($dni);
    }

    /**
     * {@inheritDoc}
     */
    public function getDni()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDni', []);

        return parent::getDni();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad($ciudad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', [$ciudad]);

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', []);

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', [$mail]);

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', []);

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechanacimiento($fechanacimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechanacimiento', [$fechanacimiento]);

        return parent::setFechanacimiento($fechanacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechanacimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechanacimiento', []);

        return parent::getFechanacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaingreso($fechaingreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaingreso', [$fechaingreso]);

        return parent::setFechaingreso($fechaingreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaingreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaingreso', []);

        return parent::getFechaingreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechareingreso($fechareingreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechareingreso', [$fechareingreso]);

        return parent::setFechareingreso($fechareingreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechareingreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechareingreso', []);

        return parent::getFechareingreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setRol($rol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRol', [$rol]);

        return parent::setRol($rol);
    }

    /**
     * {@inheritDoc}
     */
    public function getRol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRol', []);

        return parent::getRol();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setHaveLocker($haveLocker)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHaveLocker', [$haveLocker]);

        return parent::setHaveLocker($haveLocker);
    }

    /**
     * {@inheritDoc}
     */
    public function getHaveLocker()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHaveLocker', []);

        return parent::getHaveLocker();
    }

    /**
     * {@inheritDoc}
     */
    public function setHaveAsoc($haveAsoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHaveAsoc', [$haveAsoc]);

        return parent::setHaveAsoc($haveAsoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getHaveAsoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHaveAsoc', []);

        return parent::getHaveAsoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAtValue', []);

        return parent::setCreatedAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAtValue', []);

        return parent::setUpdatedAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipocuota(\CYA\YogaBundle\Entity\Tipocuota $tipocuota = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipocuota', [$tipocuota]);

        return parent::setTipocuota($tipocuota);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipocuota()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipocuota', []);

        return parent::getTipocuota();
    }

    /**
     * {@inheritDoc}
     */
    public function addAlumnocc(\CYA\YogaBundle\Entity\Alumnocc $alumnocc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAlumnocc', [$alumnocc]);

        return parent::addAlumnocc($alumnocc);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAlumnocc(\CYA\YogaBundle\Entity\Alumnocc $alumnocc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAlumnocc', [$alumnocc]);

        return parent::removeAlumnocc($alumnocc);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlumnoccs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlumnoccs', []);

        return parent::getAlumnoccs();
    }

    /**
     * {@inheritDoc}
     */
    public function addMovimiento(\CYA\YogaBundle\Entity\Movimiento $movimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMovimiento', [$movimiento]);

        return parent::addMovimiento($movimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMovimiento(\CYA\YogaBundle\Entity\Movimiento $movimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMovimiento', [$movimiento]);

        return parent::removeMovimiento($movimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovimientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovimientos', []);

        return parent::getMovimientos();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', []);

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', [$serialized]);

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', []);

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', []);

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', []);

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', []);

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombrecompleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombrecompleto', []);

        return parent::getNombrecompleto();
    }

}
